spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

camunda.bpm.admin-user:
  id: b
  password: b
